### ISSUE TITLE
Unable to run on Python 3.7

### ISSUE THREAD

**Issue by RMCampos** [rafaelmartins/blohg#11]
Hi. After manual installation of python3.7 and mod_wsgi (from source) seems not work. Traceback here: https://dpaste.com//E2Z69MUWC

Any clues?

**Comment by RMCampos** [comment]
Update: Upgraded to Debian sid and Python 3.8.5 (from source) and latest mod_wsgi (from source). Upgraded mercurial to 5.4.1, latest from Debian Sid. The problem still remains.

It seem a problem in mercurial, right? Can I report a bug? I'm not sure if it's a blohg or a mercurial issue.

**Comment by RMCampos** [comment]
Any help would be apreciated! The pip version it's not working (cannot import Babel from flask.ext.babel, no module named flask.ext) and the github version it's not working too.

**Comment by rafaelmartins** [comment]
I just tested git master with python 3.7 and mercurial, and it works nicely with both internal server and gunicorn. this issue seems to be mod_wsgi related.

Apparently, mercurial is trying to print some warning and can't do it. maybe you could try to run it manually, using the internal server and your webserver user, so you could see this warning.

**Comment by RMCampos** [comment]
Thanks a bunch! The warning was: 

> not trusting file /var/www/html/ricardocampos.blog/.hg/hgrc from untrusted user username, group groupname

Where username and groupname are my normal username and group. After changing the `/var/www/html/ricardocampos.blog/` owner to `www-data` it worked like a charm!

Thanks again!
